export { default as ProfileInputs } from './ProfileInputs'
export { default as SchoolInputs } from './SchoolInputs'
export { default as WorkingInputs } from './WorkingInputs'
export { default as MilitaryInputs } from './MilitaryInputs'
export { default as CertificateInputs } from './CertificateInputs'
export { default as LanguageInputs } from './LanguageInputs'
export { default as ProjectsInput } from './ProjectsInput'
