name: SMS-CI

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'packages/app/**'
    branches:
      - 'develop'
      - 'master'

jobs:
  SMS-app-CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9.4.0

      - run: |
          touch packages/app/.env.local
          echo "${{secrets.ENV}}" >> packages/app/.env.local

      - run: pnpm i --frozen-lockfile
      - run: pnpm build:shared
      - run: pnpm build:app

      - name: Success notification to discord
        uses: sarisia/actions-status-discord@v1.11.0
        if: ${{ success() }}
        with:
          webhook: ${{ secrets.WEBHOOK }}
          title: 'SMS app CI successfully'
          description: 'app CI success'
          content: 'success!!!'
          username: 'SMS app CI'
          url: 'https://github.com/GSM-MSG/SMS-FrontEnd'
          color: 4CAF50
          avatar_url: ${{ secrets.AVATAR_URL }}

      - name: Failure notification to discord
        uses: sarisia/actions-status-discord@v1.11.0
        if: ${{ failure() }}
        with:
          webhook: ${{ secrets.WEBHOOK }}
          title: 'SMS app CI failed'
          description: 'app CI failed'
          content: 'ㅆㅂ...'
          username: 'SMS app CI'
          url: 'https://github.com/GSM-MSG/SMS-FrontEnd'
          color: e74c3c
          avatar_url: ${{ secrets.AVATAR_URL }}
