name: SMS-CI

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'packages/shared/**'
    branches:
      - 'develop'
      - 'master'
  push:
    paths:
      - '.github/workflows/**'
      - 'packages/shared/**'
    branches:
      - 'develop'
      - 'master'

jobs:
  SMS-CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.2.0

      - run: pnpm i --frozen-lockfile
      - run: pnpm build:shared

      - env:
        title: 'SMS shared CI'
        url: 'https://github.com/GSM-MSG/SMS-FrontEnd'
        avatar_url: ${{ secrets.AVATAR_URL }}
        username: 'SMS CI bot'
        webhook: ${{ secrets.WEBHOOK }}

      - name: Success notification to discord
        uses: sarisia/actions-status-discord@v1.11.0
        if: ${{ success() }}
        with:
          webhook: $webhook
          title: '$title successfully'
          description: 'CI success'
          content: 'success!!!'
          username: $username
          url: $url
          color: 4CAF50
          avatar_url: $avatar_url

      - name: Failure notification to discord
        uses: sarisia/actions-status-discord@v1.11.0
        if: ${{ failure() }}
        with:
          webhook: $webhook
          title: '$title failed'
          description: 'CI failed'
          content: 'ㅆㅂ...'
          username: $username
          url: $url
          color: e74c3c
          avatar_url: $avatar_url
