name: SMS-CI

on:
  pull_request:
    branches:
      - 'develop'
      - 'master'

jobs:
  SMS-CI:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn' 

    - run: yarn install --frozen-lockfile
    - run: yarn build

    - name: Success notification to discord
      uses: sarisia/actions-status-discord@v1.11.0
      if: ${{ success() }}
      with:
        webhook: ${{ secrets.WEBHOOK }}
        title: "SMS CI successfully"
        description: "CI success"
        content: "success!!!"
        username: SMS CI bot
        url: "https://github.com/GSM-MSG/SMS-FrontEnd"
        color: 4CAF50
        avatar_url: ${{ secrets.AVATAR_URL }}
  
    - name: Failure notification to discord
      uses: sarisia/actions-status-discord@v1.11.0
      if: ${{ failure() }}
      with:
        webhook: ${{ secrets.WEBHOOK }}
        title: "SMS CI failed"
        description: "CI failed"
        content: "ㅆㅂ..."
        username: SMS CI bot
        url: "https://github.com/GSM-MSG/SMS-FrontEnd"
        color: e74c3c
        avatar_url: ${{ secrets.AVATAR_URL }}
      
