enum Role {
  ROLE_STUDENT = 'ROLE_STUDENT',
  ROLE_TEACHER = 'ROLE_TEACHER', // 선생님(회원가입을 하지않은)
  ROLE_PRINCIPAL = 'ROLE_TEACHER/ROLE_PRINCIPAL', // 교장선생님
  ROLE_DEPUTY_PRINCIPAL = 'ROLE_TEACHER/ROLE_DEPUTY_PRINCIPAL', // 교감선생님
  ROLE_DIRECTOR = 'ROLE_TEACHER/ROLE_DIRECTOR', // 부장선생님
  ROLE_HOMEROOM = 'ROLE_TEACHER/ROLE_HOMEROOM', // 담임선생님
}

export default Role
